name: 刷课

on:
  push:
    branches: [ main ]
  # 定时运行设置（去掉下方两行注释即可开启）
  # schedule:
  #   - cron: "0 8 * * *"

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v3

      - name: 设置python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖包
        run: pip install -r ./requirements.txt

      - name: Run main.py
        run: python main.py -u 19190282640 -p 123456HXL -l=263217129
